services:
  app:
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    ports:
      - 8070:8000
    depends_on:
      - rabbitmq
    volumes:
      - ./downloads:/apps/downloads
      - ./app:/apps/app
    networks:
      - app_network
  celery_worker:
    build: 
      context: .
      dockerfile: ./infrastructure/Dockerfile
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - BACKEND_URL=rpc://
    networks:
      - app_network
  rabbitmq:
    image: rabbitmq:4.0.4-management
    ports:
      - "56721:5672"
      - "15671:15672"  # UI RabbitMQ Management Console
    networks:
      - app_network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  app_network:
volumes:
  app_data:
  db_data:
  redis_data:
